//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppDriver.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractPerson", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAppDriver.ServiceReference.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAppDriver.ServiceReference.Driver))]
    public partial class AbstractPerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Client : WpfAppDriver.ServiceReference.AbstractPerson {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Driver", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Driver : WpfAppDriver.ServiceReference.AbstractPerson {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Report[] ReportsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KM {
            get {
                return this.KMField;
            }
            set {
                if ((this.KMField.Equals(value) != true)) {
                    this.KMField = value;
                    this.RaisePropertyChanged("KM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Report[] Reports {
            get {
                return this.ReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsField, value) != true)) {
                    this.ReportsField = value;
                    this.RaisePropertyChanged("Reports");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.ClassesOfCar ClassOfCarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Driver[] DriversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.ClassesOfCar ClassOfCar {
            get {
                return this.ClassOfCarField;
            }
            set {
                if ((this.ClassOfCarField.Equals(value) != true)) {
                    this.ClassOfCarField = value;
                    this.RaisePropertyChanged("ClassOfCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Driver[] Drivers {
            get {
                return this.DriversField;
            }
            set {
                if ((object.ReferenceEquals(this.DriversField, value) != true)) {
                    this.DriversField = value;
                    this.RaisePropertyChanged("Drivers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Driver[] DriversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Driver[] Drivers {
            get {
                return this.DriversField;
            }
            set {
                if ((object.ReferenceEquals(this.DriversField, value) != true)) {
                    this.DriversField = value;
                    this.RaisePropertyChanged("Drivers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lng {
            get {
                return this.LngField;
            }
            set {
                if ((this.LngField.Equals(value) != true)) {
                    this.LngField = value;
                    this.RaisePropertyChanged("Lng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.ClassesOfCar ClassOfCarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Driver DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Location LocationFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Location LocationToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MoneyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.ClassesOfCar ClassOfCar {
            get {
                return this.ClassOfCarField;
            }
            set {
                if ((this.ClassOfCarField.Equals(value) != true)) {
                    this.ClassOfCarField = value;
                    this.RaisePropertyChanged("ClassOfCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Done {
            get {
                return this.DoneField;
            }
            set {
                if ((this.DoneField.Equals(value) != true)) {
                    this.DoneField = value;
                    this.RaisePropertyChanged("Done");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Driver Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KM {
            get {
                return this.KMField;
            }
            set {
                if ((this.KMField.Equals(value) != true)) {
                    this.KMField = value;
                    this.RaisePropertyChanged("KM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Location LocationFrom {
            get {
                return this.LocationFromField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationFromField, value) != true)) {
                    this.LocationFromField = value;
                    this.RaisePropertyChanged("LocationFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Location LocationTo {
            get {
                return this.LocationToField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationToField, value) != true)) {
                    this.LocationToField = value;
                    this.RaisePropertyChanged("LocationTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Report : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppDriver.ServiceReference.Driver DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MoneyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppDriver.ServiceReference.Driver Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KM {
            get {
                return this.KMField;
            }
            set {
                if ((this.KMField.Equals(value) != true)) {
                    this.KMField = value;
                    this.RaisePropertyChanged("KM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassesOfCar", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    public enum ClassesOfCar : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        For4Person = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        For8Person = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForVantazh = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Changes", Namespace="http://schemas.datacontract.org/2004/07/BLL")]
    public enum Changes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FirstName = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecondName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Password = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IServiceDriver")]
    public interface IServiceDriver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/Authorization", ReplyAction="http://tempuri.org/IServiceDriver/AuthorizationResponse")]
        string Authorization(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/Authorization", ReplyAction="http://tempuri.org/IServiceDriver/AuthorizationResponse")]
        System.Threading.Tasks.Task<string> AuthorizationAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AboutDriver", ReplyAction="http://tempuri.org/IServiceDriver/AboutDriverResponse")]
        WpfAppDriver.ServiceReference.Driver AboutDriver();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AboutDriver", ReplyAction="http://tempuri.org/IServiceDriver/AboutDriverResponse")]
        System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Driver> AboutDriverAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AllCars", ReplyAction="http://tempuri.org/IServiceDriver/AllCarsResponse")]
        WpfAppDriver.ServiceReference.Car[] AllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AllCars", ReplyAction="http://tempuri.org/IServiceDriver/AllCarsResponse")]
        System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Car[]> AllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AllOrders", ReplyAction="http://tempuri.org/IServiceDriver/AllOrdersResponse")]
        WpfAppDriver.ServiceReference.Order[] AllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AllOrders", ReplyAction="http://tempuri.org/IServiceDriver/AllOrdersResponse")]
        System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Order[]> AllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AllReports", ReplyAction="http://tempuri.org/IServiceDriver/AllReportsResponse")]
        WpfAppDriver.ServiceReference.Report[] AllReports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/AllReports", ReplyAction="http://tempuri.org/IServiceDriver/AllReportsResponse")]
        System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Report[]> AllReportsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/ChangeInfo", ReplyAction="http://tempuri.org/IServiceDriver/ChangeInfoResponse")]
        string ChangeInfo(WpfAppDriver.ServiceReference.Changes changes, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/ChangeInfo", ReplyAction="http://tempuri.org/IServiceDriver/ChangeInfoResponse")]
        System.Threading.Tasks.Task<string> ChangeInfoAsync(WpfAppDriver.ServiceReference.Changes changes, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/WriteToDispatcher", ReplyAction="http://tempuri.org/IServiceDriver/WriteToDispatcherResponse")]
        string WriteToDispatcher(string Title, string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/WriteToDispatcher", ReplyAction="http://tempuri.org/IServiceDriver/WriteToDispatcherResponse")]
        System.Threading.Tasks.Task<string> WriteToDispatcherAsync(string Title, string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/ChangeCar", ReplyAction="http://tempuri.org/IServiceDriver/ChangeCarResponse")]
        string ChangeCar(int idCar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/ChangeCar", ReplyAction="http://tempuri.org/IServiceDriver/ChangeCarResponse")]
        System.Threading.Tasks.Task<string> ChangeCarAsync(int idCar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/CreateReport", ReplyAction="http://tempuri.org/IServiceDriver/CreateReportResponse")]
        string CreateReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/CreateReport", ReplyAction="http://tempuri.org/IServiceDriver/CreateReportResponse")]
        System.Threading.Tasks.Task<string> CreateReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/MyPosition", ReplyAction="http://tempuri.org/IServiceDriver/MyPositionResponse")]
        string MyPosition(WpfAppDriver.ServiceReference.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/MyPosition", ReplyAction="http://tempuri.org/IServiceDriver/MyPositionResponse")]
        System.Threading.Tasks.Task<string> MyPositionAsync(WpfAppDriver.ServiceReference.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/LogOut", ReplyAction="http://tempuri.org/IServiceDriver/LogOutResponse")]
        void LogOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDriver/LogOut", ReplyAction="http://tempuri.org/IServiceDriver/LogOutResponse")]
        System.Threading.Tasks.Task LogOutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDriverChannel : WpfAppDriver.ServiceReference.IServiceDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDriverClient : System.ServiceModel.ClientBase<WpfAppDriver.ServiceReference.IServiceDriver>, WpfAppDriver.ServiceReference.IServiceDriver {
        
        public ServiceDriverClient() {
        }
        
        public ServiceDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authorization(string Email, string Password) {
            return base.Channel.Authorization(Email, Password);
        }
        
        public System.Threading.Tasks.Task<string> AuthorizationAsync(string Email, string Password) {
            return base.Channel.AuthorizationAsync(Email, Password);
        }
        
        public WpfAppDriver.ServiceReference.Driver AboutDriver() {
            return base.Channel.AboutDriver();
        }
        
        public System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Driver> AboutDriverAsync() {
            return base.Channel.AboutDriverAsync();
        }
        
        public WpfAppDriver.ServiceReference.Car[] AllCars() {
            return base.Channel.AllCars();
        }
        
        public System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Car[]> AllCarsAsync() {
            return base.Channel.AllCarsAsync();
        }
        
        public WpfAppDriver.ServiceReference.Order[] AllOrders() {
            return base.Channel.AllOrders();
        }
        
        public System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Order[]> AllOrdersAsync() {
            return base.Channel.AllOrdersAsync();
        }
        
        public WpfAppDriver.ServiceReference.Report[] AllReports() {
            return base.Channel.AllReports();
        }
        
        public System.Threading.Tasks.Task<WpfAppDriver.ServiceReference.Report[]> AllReportsAsync() {
            return base.Channel.AllReportsAsync();
        }
        
        public string ChangeInfo(WpfAppDriver.ServiceReference.Changes changes, string param) {
            return base.Channel.ChangeInfo(changes, param);
        }
        
        public System.Threading.Tasks.Task<string> ChangeInfoAsync(WpfAppDriver.ServiceReference.Changes changes, string param) {
            return base.Channel.ChangeInfoAsync(changes, param);
        }
        
        public string WriteToDispatcher(string Title, string Message) {
            return base.Channel.WriteToDispatcher(Title, Message);
        }
        
        public System.Threading.Tasks.Task<string> WriteToDispatcherAsync(string Title, string Message) {
            return base.Channel.WriteToDispatcherAsync(Title, Message);
        }
        
        public string ChangeCar(int idCar) {
            return base.Channel.ChangeCar(idCar);
        }
        
        public System.Threading.Tasks.Task<string> ChangeCarAsync(int idCar) {
            return base.Channel.ChangeCarAsync(idCar);
        }
        
        public string CreateReport() {
            return base.Channel.CreateReport();
        }
        
        public System.Threading.Tasks.Task<string> CreateReportAsync() {
            return base.Channel.CreateReportAsync();
        }
        
        public string MyPosition(WpfAppDriver.ServiceReference.Location location) {
            return base.Channel.MyPosition(location);
        }
        
        public System.Threading.Tasks.Task<string> MyPositionAsync(WpfAppDriver.ServiceReference.Location location) {
            return base.Channel.MyPositionAsync(location);
        }
        
        public void LogOut() {
            base.Channel.LogOut();
        }
        
        public System.Threading.Tasks.Task LogOutAsync() {
            return base.Channel.LogOutAsync();
        }
    }
}
